# Generated by Django 3.2 on 2022-02-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweettooth_app', '0002_remove_recipe_excerpt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='message',
            new_name='body',
        ),
        migrations.AddField(
            model_name='recipe',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
